name: Resume CI

on:
  push:
    branches:
      - "*"

jobs:
  backend_build:
    name: backend build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
      shell: bash
      working-directory: backend
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  frontend_build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm ci
      working-directory: frontend
    - run: npm run build
      working-directory: frontend